[package]
name = "vague-search-core"
version = "0.1.0"
authors = ["Nicolas MÃ©meint <nicomem@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
